<?php

namespace DoctrineORMModule\Proxy\__CG__\Garden\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Plants extends \Garden\Entity\Plants implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'name', 'indigenous', 'height', 'origin', 'planting_date', 'blooming_start', 'blooming_end', 'details', 'present', 'features', 'habitats');
        }

        return array('__isInitialized__', 'id', 'name', 'indigenous', 'height', 'origin', 'planting_date', 'blooming_start', 'blooming_end', 'details', 'present', 'features', 'habitats');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Plants $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addFeature(\Garden\Entity\Features $feature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFeature', array($feature));

        return parent::addFeature($feature);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeatures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeatures', array());

        return parent::getFeatures();
    }

    /**
     * {@inheritDoc}
     */
    public function addHabitat(\Garden\Entity\Habitats $habitat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHabitat', array($habitat));

        return parent::addHabitat($habitat);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabitats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabitats', array());

        return parent::getHabitats();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDutchName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDutchName', array());

        return parent::getDutchName();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeight', array());

        return parent::getHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getIndigenous()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndigenous', array());

        return parent::getIndigenous();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigin', array());

        return parent::getOrigin();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlantingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlantingDate', array());

        return parent::getPlantingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getBloomingStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBloomingStart', array());

        return parent::getBloomingStart();
    }

    /**
     * {@inheritDoc}
     */
    public function getBloomingEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBloomingEnd', array());

        return parent::getBloomingEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function getDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetails', array());

        return parent::getDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function getPresent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresent', array());

        return parent::getPresent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlant($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlant', array($data));

        return parent::setPlant($data);
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray(array $values)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($values));

        return parent::exchangeArray($values);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

}
