<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->

<html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">

        <title>
        </title>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="robots" content="noindex, nofollow">

        <meta name="viewport" content="width=device-width,initial-scale=1">

        <!-- Icons -->
        <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
        <link rel="shortcut icon" href="img/favicon.ico">
        <link rel="apple-touch-icon" href="img/apple-touch-icon.png">
        <link rel="apple-touch-icon" sizes="57x57" href="img/apple-touch-icon-57x57-precomposed.png">
        <link rel="apple-touch-icon" sizes="72x72" href="img/apple-touch-icon-72x72-precomposed.png">
        <link rel="apple-touch-icon" sizes="114x114" href="img/apple-touch-icon-114x114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-precomposed.png">
        <!-- END Icons -->

        <!-- Stylesheets -->
        <!-- The roboto font is included from Google Web Fonts -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,400italic,700,700italic">

        <base href="/" />
        <link rel="stylesheet" href="../../../css/main.css" />
        <link rel="stylesheet" href="../../../css/bootstrap.css" />
        <link rel="stylesheet" href="../../../css/plugins.css" />
        <link rel="stylesheet" href="../../../css/tuinplanten.css" />

        <link rel="stylesheet" href="../../../js/jqueryUI/themes/base/jquery-ui.css" />


        <?php
        ?>
        <!-- END Stylesheets -->

        <!-- Modernizr (Browser feature detection library) & Respond.js (Enable responsive CSS code on browsers that don't support them) -->
        <script src="../../../js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    </head>

    <body class="fixed980">
        <!-- Page Container -->
        <div id="page-container">

            <header class="">
                <div id="logo"></div>
                <?php
                ?>
                <h1>Tuinplanten</h1>
            </header>
            <!-- END Header -->

            <div id="container">
                <div id="site">
                    <div id="content_container">
                        <?php echo $this->layout()->content ?>
                    </div>
                    <div id="footer">
                    </div>
                </div>
            </div>

            <h2>Footer</h2>
            <!-- Excanvas for Flot (Charts plugin) support on IE8 -->
                    <!--[if lte IE 8]><script src="js/helpers/excanvas.min.js"></script><![endif]-->

            <!-- Jquery library from Google ... -->
            <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
            <!-- ... but if something goes wrong get Jquery from local file -->
            <script>!window.jQuery && document.write(unescape('%3Cscript src="js/vendor/jquery-1.8.3.min.js"%3E%3C/script%3E'));</script>

            <!-- Bootstrap.js -->
            <script src="../../../js/vendor/bootstrap.min.js"></script>

            <!-- Include Google Maps API for global use -->
            <script src="http://maps.google.com/maps/api/js?sensor=true"></script>

            <!-- Jquery plugins and custom javascript code -->
            <script src="../../../js/plugins.js"></script>
            <script src="../../../js/main.js"></script>
    </body>
</html>